# This file can be used to override defaults for multirun arguments.
# These will be overridden by command-line arguments

maxNumberOfRuns: 5
executeWithGui: false
randomSeed: 12345
startYear: 2018
endYear: 2025
popSize: 75000

# For arguments to pass to the SimPathsModel itself:
model_args:
#    labourMarketCovid19On: false
#    enableIntertemporalOptimisations: false
