# This file can be used to override defaults for multirun arguments.
# These will be overridden by command-line arguments

maxNumberOfRuns: 3
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2020
popSize: 170000

# For arguments to pass to the SimPathsModel itself:
# Current model defaults can be overridden by uncommenting/changing
model_args:
#    maxAge: 130
#    fixTimeTrend: true
#    timeTrendStopsIn: 2017
#    fixRandomSeed: true
#    sIndexTimeWindow: 5
#    sIndexAlpha: 2
#    sIndexDelta: 0
#    savingRate: 0
#    initialisePotentialEarningsFromDatabase: true
#    useWeights: false
#    useSBAMMatching:
#    projectMortality: true
#    labourMarketCovid19On: false
#    projectFormalChildcare: true
#    donorPoolAveraging: true
    alignEmployment: false
    projectSocialCare: false
    enableIntertemporalOptimisations: true
    responsesToLowWageOffer: true
    saveBehaviour: false
#    saveImperfectTaxDBMatches: false
#    useSavedBehaviour: false
#    readGrid: "laptop serial"
#    employmentOptionsOfPrincipalWorker: 3
#    employmentOptionsOfSecondaryWorker: 3
#    responsesToEducation: true
#    responsesToRetirement: false
#    responsesToHealth: true
#    responsesToDisability: false
#    minAgeForPoorHealth: 50
#    responsesToRegion: false
#    alignPopulation: false
#    alignCohabitation: false
#    alignFertility: false
#    alignEducation: false
#    alignInSchool: false
#    flagDefaultToTimeSeriesAverages: true

innovation_args:
    randomSeedInnov: false
    labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0