# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

countryString: "United Kingdom"
startYear: 2019
endYear: 2070
maxNumberOfRuns: 1
executeWithGui: false

# Arguments passed to the SimPathsModel
model_args:
    popSize: 170000
    maxAge: 130
    fixTimeTrend: true
    timeTrendStopsIn: 2021
    flagDefaultToTimeSeriesAverages: true
    saveImperfectTaxDBMatches: true
    enableIntertemporalOptimisations: true
    saveBehaviour: true

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
    randomSeedInnov: false
    flagDatabaseSetup: true
#    intertemporalElasticityInnov: true
#    labourSupplyElasticityInnov: true
#    flagUpdateDatabase: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0