# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

maxNumberOfRuns: 3
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2019
popSize: 170000

# Arguments passed to the SimPathsModel
model_args:
    alignPopulation: true
    enableIntertemporalOptimisations: true
    responsesToLowWageOffer: true
    projectSocialCare: false
    saveBehaviour: false
    responsesToDisability: false
    saveImperfectTaxDBMatches: false
    flagSuppressSocialCareCosts: false
    flagSuppressChildcareCosts: false
    flagDefaultToTimeSeriesAverages: true
    useSavedBehaviour: false
    readGrid: "test"


# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
    randomSeedInnov: false
#    intertemporalElasticityInnov: true
    labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0