# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

maxNumberOfRuns: 1
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2069
popSize: 170000

# Arguments passed to the SimPathsModel
model_args:
#    maxAge: 130
#    fixTimeTrend: true
#    timeTrendStopsIn: 2017
#    fixRandomSeed: true
#    sIndexTimeWindow: 5
#    sIndexAlpha: 2
#    sIndexDelta: 0
#    savingRate: 0
#    initialisePotentialEarningsFromDatabase: true
#    useWeights: false
#    useSBAMMatching:
#    projectMortality: true
#    labourMarketCovid19On: false
#    projectFormalChildcare: true
#    donorPoolAveraging: true
    alignEmployment: false
    alignCohabitation: false
    enableIntertemporalOptimisations: true
    responsesToLowWageOffer: true
    projectSocialCare: true
    saveBehaviour: true
    flagDefaultToTimeSeriesAverages: false
    responsesToDisability: true
    saveImperfectTaxDBMatches: true
    flagSuppressCareCosts: false
    useSavedBehaviour: false
    readGrid: "base simulation"
#    employmentOptionsOfPrincipalWorker: 3
#    employmentOptionsOfSecondaryWorker: 3
#    responsesToEducation: true
#    responsesToRetirement: false
#    responsesToHealth: true
#    minAgeForPoorHealth: 50
#    responsesToRegion: false
#    alignPopulation: false
#    alignFertility: false
#    alignEducation: false
#    alignInSchool: false
#    flagDefaultToTimeSeriesAverages: true

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
  randomSeedInnov: false
#  intertemporalElasticityInnov: false
#  labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0