# CONFIG FILE TO RUN IGNORE COSTS SIMULATION FOR SOCIAL CARE ANALYSIS
# MODEL INCLUDES RESPONSES THAT ASSUME NO CARE COSTS BUT WHERE COSTS EXIST AND POPULATION ALIGNMENT
maxNumberOfRuns: 1
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2069
popSize: 5000

# Arguments passed to the SimPathsModel
model_args:
    alignFertility: false
    alignCohabitation: false
    alignPopulation: true
    enableIntertemporalOptimisations: true
    responsesToLowWageOffer: true
    projectSocialCare: true
    saveBehaviour: true
    responsesToDisability: true
    saveImperfectTaxDBMatches: false
    flagSuppressSocialCareCosts: false
    flagSuppressChildcareCosts: false
    useSavedBehaviour: true
    readGrid: "zerocosts"

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
  randomSeedInnov: false
#  intertemporalElasticityInnov: false
#  labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0