# CONFIG FILE TO CALIBRATE PREFERENCE PARAMETERS FOR SOCIAL CARE ANALYSIS
# MODEL INCLUDES RATIONAL RESPONSES WITHOUT CARE AND POPULATION ALIGNMENT
maxNumberOfRuns: 1
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2020
popSize: 170000

# Arguments passed to the SimPathsModel
model_args:
    alignFertility: false
    alignCohabitation: false
    alignPopulation: false
    enableIntertemporalOptimisations: true
    responsesToLowWageOffer: true
    projectSocialCare: false
    saveBehaviour: false
    responsesToDisability: false
    saveImperfectTaxDBMatches: false
    flagSuppressSocialCareCosts: false
    flagSuppressChildcareCosts: false
    useSavedBehaviour: false
    readGrid: "base"

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
  randomSeedInnov: false
#  intertemporalElasticityInnov: false
#  labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0